/*
Copyright 2026 Kunal Khare.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.
//
// This file is produced by `make generate`, which runs:
//   controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./api/..."
//
// If you add or change a field on any type in fqdnnetworkpolicy_types.go,
// run `make generate` again rather than hand-editing this file — that's
// the whole point of wiring up controller-gen instead of maintaining
// deepcopy logic by hand.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicy) DeepCopyInto(out *FQDNNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new FQDNNetworkPolicy.
func (in *FQDNNetworkPolicy) DeepCopy() *FQDNNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FQDNNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicyList) DeepCopyInto(out *FQDNNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FQDNNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new FQDNNetworkPolicyList.
func (in *FQDNNetworkPolicyList) DeepCopy() *FQDNNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is a deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FQDNNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicySpec) DeepCopyInto(out *FQDNNetworkPolicySpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]FQDNRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolutionTTLOverride != nil {
		in, out := &in.ResolutionTTLOverride, &out.ResolutionTTLOverride
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new FQDNNetworkPolicySpec.
func (in *FQDNNetworkPolicySpec) DeepCopy() *FQDNNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicyStatus) DeepCopyInto(out *FQDNNetworkPolicyStatus) {
	*out = *in
	if in.ResolvedHosts != nil {
		in, out := &in.ResolvedHosts, &out.ResolvedHosts
		*out = make([]ResolvedHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new FQDNNetworkPolicyStatus.
func (in *FQDNNetworkPolicyStatus) DeepCopy() *FQDNNetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNRule) DeepCopyInto(out *FQDNRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PolicyPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new FQDNRule.
func (in *FQDNRule) DeepCopy() *FQDNRule {
	if in == nil {
		return nil
	}
	out := new(FQDNRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelectorSpec) DeepCopyInto(out *PodSelectorSpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new PodSelectorSpec.
func (in *PodSelectorSpec) DeepCopy() *PodSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(PodSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPort) DeepCopyInto(out *PolicyPort) {
	*out = *in
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new PolicyPort.
func (in *PolicyPort) DeepCopy() *PolicyPort {
	if in == nil {
		return nil
	}
	out := new(PolicyPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is a deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedHost) DeepCopyInto(out *ResolvedHost) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LastSeen.DeepCopyInto(&out.LastSeen)
}

// DeepCopy is a deepcopy function, copying the receiver, creating a new ResolvedHost.
func (in *ResolvedHost) DeepCopy() *ResolvedHost {
	if in == nil {
		return nil
	}
	out := new(ResolvedHost)
	in.DeepCopyInto(out)
	return out
}
