//go:build !ignore_autogenerated

/*
Copyright 2026 Kunal Khare.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFQDNNetworkPolicy) DeepCopyInto(out *ClusterFQDNNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFQDNNetworkPolicy.
func (in *ClusterFQDNNetworkPolicy) DeepCopy() *ClusterFQDNNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterFQDNNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFQDNNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFQDNNetworkPolicyList) DeepCopyInto(out *ClusterFQDNNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterFQDNNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFQDNNetworkPolicyList.
func (in *ClusterFQDNNetworkPolicyList) DeepCopy() *ClusterFQDNNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterFQDNNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterFQDNNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFQDNNetworkPolicySpec) DeepCopyInto(out *ClusterFQDNNetworkPolicySpec) {
	*out = *in
	in.NamespaceSelector.DeepCopyInto(&out.NamespaceSelector)
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]FQDNRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolutionTTLOverride != nil {
		in, out := &in.ResolutionTTLOverride, &out.ResolutionTTLOverride
		*out = new(int32)
		**out = **in
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFQDNNetworkPolicySpec.
func (in *ClusterFQDNNetworkPolicySpec) DeepCopy() *ClusterFQDNNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterFQDNNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterFQDNNetworkPolicyStatus) DeepCopyInto(out *ClusterFQDNNetworkPolicyStatus) {
	*out = *in
	if in.ResolvedHosts != nil {
		in, out := &in.ResolvedHosts, &out.ResolvedHosts
		*out = make([]ResolvedHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AffectedNamespaces != nil {
		in, out := &in.AffectedNamespaces, &out.AffectedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterFQDNNetworkPolicyStatus.
func (in *ClusterFQDNNetworkPolicyStatus) DeepCopy() *ClusterFQDNNetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterFQDNNetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSSecurityMetadata) DeepCopyInto(out *DNSSecurityMetadata) {
	*out = *in
	if in.ResolverResults != nil {
		in, out := &in.ResolverResults, &out.ResolverResults
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSSecurityMetadata.
func (in *DNSSecurityMetadata) DeepCopy() *DNSSecurityMetadata {
	if in == nil {
		return nil
	}
	out := new(DNSSecurityMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNEgressObservation) DeepCopyInto(out *FQDNEgressObservation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNEgressObservation.
func (in *FQDNEgressObservation) DeepCopy() *FQDNEgressObservation {
	if in == nil {
		return nil
	}
	out := new(FQDNEgressObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FQDNEgressObservation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNEgressObservationList) DeepCopyInto(out *FQDNEgressObservationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FQDNEgressObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNEgressObservationList.
func (in *FQDNEgressObservationList) DeepCopy() *FQDNEgressObservationList {
	if in == nil {
		return nil
	}
	out := new(FQDNEgressObservationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FQDNEgressObservationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNEgressObservationSpec) DeepCopyInto(out *FQDNEgressObservationSpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	out.ObservationWindow = in.ObservationWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNEgressObservationSpec.
func (in *FQDNEgressObservationSpec) DeepCopy() *FQDNEgressObservationSpec {
	if in == nil {
		return nil
	}
	out := new(FQDNEgressObservationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNEgressObservationStatus) DeepCopyInto(out *FQDNEgressObservationStatus) {
	*out = *in
	if in.ObservedDomains != nil {
		in, out := &in.ObservedDomains, &out.ObservedDomains
		*out = make([]ObservedDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNEgressObservationStatus.
func (in *FQDNEgressObservationStatus) DeepCopy() *FQDNEgressObservationStatus {
	if in == nil {
		return nil
	}
	out := new(FQDNEgressObservationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicy) DeepCopyInto(out *FQDNNetworkPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNNetworkPolicy.
func (in *FQDNNetworkPolicy) DeepCopy() *FQDNNetworkPolicy {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FQDNNetworkPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicyList) DeepCopyInto(out *FQDNNetworkPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FQDNNetworkPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNNetworkPolicyList.
func (in *FQDNNetworkPolicyList) DeepCopy() *FQDNNetworkPolicyList {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FQDNNetworkPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicySpec) DeepCopyInto(out *FQDNNetworkPolicySpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]FQDNRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResolutionTTLOverride != nil {
		in, out := &in.ResolutionTTLOverride, &out.ResolutionTTLOverride
		*out = new(int32)
		**out = **in
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecuritySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNNetworkPolicySpec.
func (in *FQDNNetworkPolicySpec) DeepCopy() *FQDNNetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNNetworkPolicyStatus) DeepCopyInto(out *FQDNNetworkPolicyStatus) {
	*out = *in
	if in.ResolvedHosts != nil {
		in, out := &in.ResolvedHosts, &out.ResolvedHosts
		*out = make([]ResolvedHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedUnpoliciedDomains != nil {
		in, out := &in.ObservedUnpoliciedDomains, &out.ObservedUnpoliciedDomains
		*out = make([]ObservedDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNNetworkPolicyStatus.
func (in *FQDNNetworkPolicyStatus) DeepCopy() *FQDNNetworkPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(FQDNNetworkPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNRule) DeepCopyInto(out *FQDNRule) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]PolicyPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNRule.
func (in *FQDNRule) DeepCopy() *FQDNRule {
	if in == nil {
		return nil
	}
	out := new(FQDNRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPEnrichment) DeepCopyInto(out *IPEnrichment) {
	*out = *in
	if in.EnrichedAt != nil {
		in, out := &in.EnrichedAt, &out.EnrichedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPEnrichment.
func (in *IPEnrichment) DeepCopy() *IPEnrichment {
	if in == nil {
		return nil
	}
	out := new(IPEnrichment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedDomain) DeepCopyInto(out *ObservedDomain) {
	*out = *in
	in.FirstSeen.DeepCopyInto(&out.FirstSeen)
	in.LastSeen.DeepCopyInto(&out.LastSeen)
	if in.ObservedPorts != nil {
		in, out := &in.ObservedPorts, &out.ObservedPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedDomain.
func (in *ObservedDomain) DeepCopy() *ObservedDomain {
	if in == nil {
		return nil
	}
	out := new(ObservedDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelectorSpec) DeepCopyInto(out *PodSelectorSpec) {
	*out = *in
	in.PodSelector.DeepCopyInto(&out.PodSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSelectorSpec.
func (in *PodSelectorSpec) DeepCopy() *PodSelectorSpec {
	if in == nil {
		return nil
	}
	out := new(PodSelectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyPort) DeepCopyInto(out *PolicyPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyPort.
func (in *PolicyPort) DeepCopy() *PolicyPort {
	if in == nil {
		return nil
	}
	out := new(PolicyPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedHost) DeepCopyInto(out *ResolvedHost) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LastSeen.DeepCopyInto(&out.LastSeen)
	if in.CNAMEChain != nil {
		in, out := &in.CNAMEChain, &out.CNAMEChain
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(DNSSecurityMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.IPEnrichments != nil {
		in, out := &in.IPEnrichments, &out.IPEnrichments
		*out = make(map[string]IPEnrichment, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedHost.
func (in *ResolvedHost) DeepCopy() *ResolvedHost {
	if in == nil {
		return nil
	}
	out := new(ResolvedHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySpec) DeepCopyInto(out *SecuritySpec) {
	*out = *in
	if in.MaxCNAMEDepth != nil {
		in, out := &in.MaxCNAMEDepth, &out.MaxCNAMEDepth
		*out = new(int32)
		**out = **in
	}
	if in.BlockPrivateIPs != nil {
		in, out := &in.BlockPrivateIPs, &out.BlockPrivateIPs
		*out = new(bool)
		**out = **in
	}
	if in.BlockLoopback != nil {
		in, out := &in.BlockLoopback, &out.BlockLoopback
		*out = new(bool)
		**out = **in
	}
	if in.BlockLinkLocal != nil {
		in, out := &in.BlockLinkLocal, &out.BlockLinkLocal
		*out = new(bool)
		**out = **in
	}
	if in.BlockOnDivergence != nil {
		in, out := &in.BlockOnDivergence, &out.BlockOnDivergence
		*out = new(bool)
		**out = **in
	}
	if in.MinResolverAgreement != nil {
		in, out := &in.MinResolverAgreement, &out.MinResolverAgreement
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySpec.
func (in *SecuritySpec) DeepCopy() *SecuritySpec {
	if in == nil {
		return nil
	}
	out := new(SecuritySpec)
	in.DeepCopyInto(out)
	return out
}
